import { Inter, Poppins } from "next/font/google";
import "@/assets/css/globals.scss";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins(
  { 
    subsets: ['latin'],
    weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  },
);

export const metadata = {
  title: "Watch shop",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
